# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

version: '2'

services:
  bmo-web.vm:
    image: bmo
    command: dev_httpd
    tmpfs:
      - /tmp
      - /run
    environment:
      - 'BMO_inbound_proxies=*'
      - BMO_db_host=bmo-db.vm
      - BMO_db_name=bugs
      - BMO_db_pass=bugs
      - BMO_db_user=bugs
      - BMO_memcached_namespace=bugzilla
      - BMO_memcached_servers=memcached:11211
      - BMO_urlbase=http://bmo-web.vm/
      - BUGZILLA_ALLOW_INSECURE_HTTP=1
      - BZ_ANSWERS_FILE=/app/conf/checksetup_answers.txt
      - BZ_QA_ANSWERS_FILE=/app/.circleci/checksetup_answers.txt
      - BZ_QA_CONF_FILE=/app/.circleci/selenium_test.conf
      - BZ_QA_CONFIG=1
      - HTTP_BACKEND=simple
      - LOCALCONFIG_ENV=1
      - LOG4PERL_CONFIG_FILE=log4perl-docker.conf
      - PORT=80
      - TWD_HOST=selenium
      - TWD_PORT=4444
      - TWD_BROWSER=firefox
    depends_on:
      - bmo-db.vm
      - memcached
      - tinyproxy
      - selenium

  bmo-db.vm:
    image: mozillabteam/bmo-mysql:5.6
    logging:
      driver: "none"
    environment:
      - MYSQL_DATABASE=bugs
      - MYSQL_USER=bugs
      - MYSQL_PASSWORD=bugs
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  memcached:
    image: memcached:latest

  tinyproxy:
    image: mozillabteam/tinyproxy
    ports:
      - "1090:1090"

  selenium:
    image: selenium/standalone-firefox:3.141.59
